FROM alpine as builder
# COPY --from=shareinto/php:fat /usr/local/bin/php /usr/local/bin/php
RUN apk add php
RUN rm /lib/libcrypto.so.1.1 && rm -r /lib/apk && rm /lib/libssl.so.1.1 && rm /lib/libapk.so.3.12.0
# RUN cp /usr/bin/php8 /dist
# RUN cp /lib /dist

FROM scratch
COPY --from=0 /usr/bin/php8 /usr/bin/php
COPY --from=0 /usr/lib /usr/lib
COPY --from=0 /lib /lib
COPY --from=shareinto/php:fat /hello1.php /hello1.php

CMD ["/usr/bin/php", "-S", "0.0.0.0:80", "/hello1.php"]